apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  AUTH_APP_PORT: {{ .Values.config.authAppPort }}
  BALANCE_APP_PORT: {{ .Values.config.balanceAppPort }}
  VERIFICATION_PORT: {{ .Values.config.verificationPort }}
  KAFKA_PORT: {{ .Values.config.kafkaPort }}
  AUTH_APP_HOST: {{ .Values.config.authAppHost }}
  BALANCE_APP_HOST: {{ .Values.config.balanceAppHost }}
  VERIFICATION_HOST: {{ .Values.config.verificationHost }}
  KAFKA_HOST: {{ .Values.config.kafkaHost }}
  POSTGRES_HOST: {{ .Values.config.postgresHost }}
  POSTGRES_PORT: {{ .Values.config.postgresPort }}
  POSTGRES_DB_NAME: {{ .Values.config.postgresDbName }}
  TOKEN_TTL: {{ .Values.config.tokenTTL }}
  VERIFIED_BALANCE: {{ .Values.config.verifiedBalance }}
  UNVERIFIED_BALANCE: {{ .Values.config.unverifiedBalance }}
  FIRST_USER_FIELD: {{.Values.config.firstUserField }}
  SECOND_USER_FIELD: {{ .Values.config.secondUserField }}
