apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.authAppHost }}
  labels:
    app: {{ .Values.config.authAppHost }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.config.authAppHost }}
  template:
    metadata:
      name: {{ .Values.config.authAppHost }}
      labels:
        app: {{ .Values.config.authAppHost }}
    spec:
      containers:
        - name: {{ .Values.config.authAppHost }}
          image: {{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: {{ int .Values.config.authAppPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.auth.probes.liveness.path }}
              port: {{ int .Values.config.authAppPort }}
            initialDelaySeconds: {{ .Values.auth.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.auth.probes.readiness.path }}
              port: {{ int .Values.config.authAppPort }}
            initialDelaySeconds: {{ .Values.auth.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.readiness.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.auth.resources.requests.memory }}
              cpu: {{ .Values.auth.resources.requests.cpu }}
            limits:
              memory: {{.Values.auth.resources.limits.memory}}
              cpu: {{.Values.auth.resources.limits.cpu}}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: gran-cc-secrets
          volumeMounts:
            - mountPath: /app/photo_storage
              name: photo-storage
      volumes:
        - name: photo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
