apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.balanceAppHost }}
  labels:
    app: {{ .Values.config.balanceAppHost }}
spec:
  replicas: {{ .Values.balance.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.config.balanceAppHost }}
  template:
    metadata:
      name: {{ .Values.config.balanceAppHost }}
      labels:
        app: {{ .Values.config.balanceAppHost }}
    spec:
      containers:
        - name: {{ .Values.config.balanceAppHost }}
          image: {{ .Values.balance.image.repository }}:{{ .Values.balance.image.tag }}
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: {{ int .Values.config.balanceAppPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.balance.probes.liveness.path }}
              port: {{ int .Values.config.balanceAppPort }}
            initialDelaySeconds: {{ .Values.balance.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.balance.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.balance.probes.readiness.path }}
              port: {{ int .Values.config.balanceAppPort }}
            initialDelaySeconds: {{ .Values.balance.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.balance.probes.readiness.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.balance.resources.requests.memory }}
              cpu: {{ .Values.balance.resources.requests.cpu }}
            limits:
              memory: {{ .Values.balance.resources.limits.memory }}
              cpu: {{ .Values.balance.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: gran-cc-secrets
