apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.verificationHost }}
  labels:
    app: {{ .Values.config.verificationHost }}
spec:
  replicas: {{ .Values.verify.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.config.verificationHost }}
  template:
    metadata:
      name: {{ .Values.config.verificationHost }}
      labels:
        app: {{ .Values.config.verificationHost }}
    spec:
      containers:
        - name: {{ .Values.config.verificationHost }}
          image: {{ .Values.verify.image.repository }}:{{ .Values.verify.image.tag }}
          ports:
            - containerPort: {{ int .Values.config.verificationPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.verify.probes.liveness.path }}
              port: {{ int .Values.config.verificationPort }}
            initialDelaySeconds: {{ .Values.verify.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.verify.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.verify.probes.readiness.path }}
              port: {{ int .Values.config.verificationPort }}
            initialDelaySeconds: {{ .Values.verify.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.verify.probes.readiness.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.verify.resources.requests.memory }}
              cpu: {{ .Values.verify.resources.requests.cpu }}
            limits:
              memory: {{ .Values.verify.resources.limits.memory }}
              cpu: {{ .Values.verify.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: gran-cc-secrets
          volumeMounts:
            - mountPath: /app/photo_storage
              name: photo-storage
      volumes:
        - name: photo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
