apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.balanceAppHost }}
spec:
  selector:
    app: {{ .Values.config.balanceAppHost }}
  ports:
    - protocol: TCP
      port: {{ .Values.config.balanceAppPort }}
      targetPort: {{ .Values.config.balanceAppPort }}
