default:
  image: python:3.10-slim


stages:
  - tests
  - linters


Tests:
  stage: tests
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - apt-get -y update && apt-get -y install libgl1
    - apt-get -y update && apt-get -y install libglib2.0-0
  script:
    - poetry run pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "week2_task1"
      changes:
        - "**/*.py"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "week2_task1"
      when: manual

Linters:
  stage: linters
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install --without ml
  script:
    - poetry run flake8
    - poetry run mypy .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "week2_task1"
      changes:
        - "**/*.py"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "week2_task1"
      when: manual
