default:
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"

stages:
  - linters
  - tests

Tests:
  stage: tests
  before_script:
    - poetry install
  script:
    - poetry run pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "week2_task1"
      changes:
        - "**/*.py"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "week2_task1"
      when: manual

Linters:
  stage: linters
  before_script:
    - poetry install --no-root
  script:
    - poetry run flake8
    - poetry run mypy .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "week2_task1"
      changes:
        - "**/*.py"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "week2_task1"
      when: manual
