version: '3'

networks:
  cc_main_net:
    driver: bridge
  cc_balance_net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - cc_main_net

  kafka:
    build:
      context: .
      dockerfile: docker/Dockerfile-kafka
    image: custom-kafka:latest
    restart: always
    healthcheck:
      test: /healthcheck-kafka.sh
      interval: 30s
      timeout: 5s
      retries: 6
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - cc_main_net

  cc_auth:
    build:
      context: .
      dockerfile: docker/Dockerfile-auth
    image: cc_auth:latest
    restart: always
    ports:
      - "24001:24001"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - photo_storage:/app/photo_storage/
    networks:
      - cc_main_net


  cc_balance:
    build:
      context: .
      dockerfile: docker/Dockerfile-balance
    image: cc_balance:latest
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - cc_main_net
      - cc_balance_net

  cc_verify:
    build:
      context: .
      dockerfile: docker/Dockerfile-verify
    image: cc_verify:latest
    restart: always
    volumes:
      - photo_storage:/app/photo_storage
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - cc_main_net

volumes:
  photo_storage:
