version: '3'

networks:
  cc_main_net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/zookeeper/bin/zkServer.sh status | grep 'Mode: standalone' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cc_main_net

  kafka:
    build:
      context: .
      dockerfile: docker/Dockerfile-kafka
    image: custom-kafka:latest
    restart: always
    healthcheck:
      test: /healthcheck-kafka.sh
      interval: 30s
      timeout: 5s
      retries: 6
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - cc_main_net

  cc_postgres:
    image: bitnami/postgresql:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shift_cc
      POSTGRES_PASSWORD: shift_cc_pass
      POSTGRES_DB: shift_cc_db
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - cc_main_net

  cc_auth:
    build:
      context: .
      dockerfile: docker/Dockerfile-auth
    image: cc_auth:latest
    restart: always
    ports:
      - "24001:24001"
    depends_on:
      kafka:
        condition: service_healthy
      cc_postgres:
        condition: service_started
    volumes:
      - photo_storage:/app/photo_storage/
    networks:
      - cc_main_net


  cc_balance:
    build:
      context: .
      dockerfile: docker/Dockerfile-balance
    image: cc_balance:latest
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      cc_postgres:
        condition: service_started
    networks:
      - cc_main_net

  cc_verify:
    build:
      context: .
      dockerfile: docker/Dockerfile-verify
    image: cc_verify:latest
    restart: always
    volumes:
      - photo_storage:/app/photo_storage
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - cc_main_net

volumes:
  photo_storage:
  postgres_data:
