apiVersion: v1
kind: Pod
metadata:
  name: gran-cc-auth-migrations
spec:
  containers:
  - name: gran-cc-auth-migrations
    image: registry.gitlab.com/shift-python/y2023/homeworks/gramatchikov-a/credit_card/cc_auth:latest
    command: ["python", "create_db.py"]
    envFrom:
    - configMapRef:
        name: gran-cc-configmap
    - secretRef:
        name: gran-cc-secrets
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "250m"
  restartPolicy: Never
