apiVersion: batch/v1
kind: Job
metadata:
  name: gran-cc-auth-migrations
spec:
  template:
    spec:
      containers:
      - name: gran-cc-auth-migrations
        image: registry.gitlab.com/shift-python/y2023/homeworks/gramatchikov-a/credit_card/cc_auth:latest
        command: ["poetry", "run", "alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: gran-cc-configmap
        - secretRef:
            name: gran-cc-secrets
      restartPolicy: OnFailure
