apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gran-photo-storage-pvc
spec:
  storageClassName: yc-network-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
