apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gran-photo-storage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: disk-csi-driver.mks.ycloud.io
spec:
  storageClassName: yc-network-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
