"""Balance Initial migration

Revision ID: 82b113162ce5
Revises: 3aae700c2fde
Create Date: 2023-09-29 13:09:23.787530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b113162ce5'
down_revision: Union[str, None] = '3aae700c2fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_number', sa.String(length=18), nullable=False),
    sa.Column('card_limit', sa.BigInteger(), nullable=False),
    sa.Column('card_balance', sa.BigInteger(), nullable=False),
    sa.Column('card_first_name', sa.String(length=50), nullable=True),
    sa.Column('card_second_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('balance_logs',
    sa.Column('card_number_id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('balance_before', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('changes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['card_number_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_number_id', 'datetime_utc')
    )
    op.create_table('common_logs',
    sa.Column('card_number_id', sa.BigInteger(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('limit_before', sa.BigInteger(), nullable=False),
    sa.Column('limit_after', sa.BigInteger(), nullable=False),
    sa.Column('changes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['card_number_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_number_id', 'datetime_utc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('common_logs')
    op.drop_table('balance_logs')
    op.drop_table('cards')
    # ### end Alembic commands ###
