FROM python:3.10-slim as python-base

LABEL authors="megagran"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.5.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"

ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

FROM python-base as builder_2

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    curl \
    build-essential

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR $PYSETUP_PATH
COPY poetry.lock pyproject.toml ./

RUN poetry install

FROM python-base as final

WORKDIR /app
COPY --from=builder_2 $PYSETUP_PATH $PYSETUP_PATH

COPY ./config/ ./config/
COPY ./credit_card_verify/ ./credit_card_verify/
COPY ./photo_storage/ ./photo_storage/
COPY main_verify.py ./

VOLUME ["/app/photo_storage/"]

CMD ["python", "main_verify.py"]
