components:
  schemas:
    BalanceLogModel:
      description: Класс для логов баланса.
      properties:
        after:
          title: After
          type: string
        before:
          title: Before
          type: string
        card_number:
          title: Card Number
          type: string
        changes:
          title: Changes
          type: string
        datetime_utc:
          format: date-time
          title: Datetime Utc
          type: string
      required:
      - card_number
      - before
      - after
      - changes
      - datetime_utc
      title: BalanceLogModel
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    TransactionRequest:
      description: Схема для транзакций.
      properties:
        balance:
          title: Balance
          type: string
        card_number:
          title: Card Number
          type: string
      required:
      - card_number
      - balance
      title: TransactionRequest
      type: object
    UserBalanceRequest:
      description: Balance response schema.
      properties:
        balance:
          title: Balance
          type: string
        card_number:
          title: Card Number
          type: string
      required:
      - card_number
      - balance
      title: UserBalanceRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/balance:
    get:
      description: "Получение баланса.\n\nArgs:\n    card_number (str): Номер карты.\n\
        \nReturns:\n    UserBalanceRequest: Баланс."
      operationId: read_balance_api_balance_get
      parameters:
      - in: query
        name: card_number
        required: true
        schema:
          title: Card Number
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBalanceRequest'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read Balance
      tags:
      - balance
  /api/balance/history:
    get:
      description: "Получение истории баланса.\n\nArgs:\n    card_number (str): Номер\
        \ карты.\n    from_date (datetime): Дата начала.\n    to_date (datetime):\
        \ Дата конца.\n\nReturns:\n    list[BalanceLogModel]: История баланса."
      operationId: read_balance_history_api_balance_history_get
      parameters:
      - in: query
        name: card_number
        required: true
        schema:
          title: Card Number
          type: string
      - in: query
        name: from_date
        required: true
        schema:
          format: date-time
          title: From Date
          type: string
      - in: query
        name: to_date
        required: true
        schema:
          format: date-time
          title: To Date
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BalanceLogModel'
                title: Response Read Balance History Api Balance History Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read Balance History
      tags:
      - balance
  /api/deposit:
    post:
      description: "Эндпоинт для пополнения карты.\n\nArgs:\n    card_number (str):\
        \ Номер карты.\n    amount (Decimal): Сумма.\n\nReturns:\n    TransactionRequest:\
        \ Новый баланс."
      operationId: deposit_api_deposit_post
      parameters:
      - in: query
        name: card_number
        required: true
        schema:
          title: Card Number
          type: string
      - in: query
        name: amount
        required: true
        schema:
          anyOf:
          - type: number
          - type: string
          title: Amount
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRequest'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Deposit
      tags:
      - transactions
  /api/verify:
    post:
      description: "Эндпоинт для повышения лимита после верификации.\n\nArgs:\n  \
        \  card_number (str): Номер карты.\n    verified (bool): Подтверждение верификации."
      operationId: verify_api_verify_post
      parameters:
      - in: query
        name: card_number
        required: true
        schema:
          title: Card Number
          type: string
      - in: query
        name: verified
        required: true
        schema:
          title: Verified
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Verify
      tags:
      - transactions
  /api/withdrawal:
    post:
      description: "Эндпоинт для снятия денег с карты.\n\nArgs:\n    card_number (str):\
        \ Номер карты.\n    amount (Decimal): Сумма.\n\nReturns:\n    TransactionRequest:\
        \ Новый баланс."
      operationId: withdrawal_api_withdrawal_post
      parameters:
      - in: query
        name: card_number
        required: true
        schema:
          title: Card Number
          type: string
      - in: query
        name: amount
        required: true
        schema:
          anyOf:
          - type: number
          - type: string
          title: Amount
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRequest'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Withdrawal
      tags:
      - transactions
