openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/balance:
    get:
      tags:
        - balance
      summary: Read Balance
      description: |-
        Получение баланса.

        Args:
            card_number (str): Номер карты.

        Returns:
            UserBalanceRequest: Баланс.
      operationId: read_balance_api_balance_get
      parameters:
        - name: card_number
          in: query
          required: true
          schema:
            type: string
            title: Card Number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBalanceRequest'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/balance/history:
    get:
      tags:
        - balance
      summary: Read Balance History
      description: |-
        Получение истории баланса.

        Args:
            card_number (str): Номер карты.
            from_date (datetime): Дата начала.
            to_date (datetime): Дата конца.

        Returns:
            list[BalanceLogModel]: История баланса.
      operationId: read_balance_history_api_balance_history_get
      parameters:
        - name: card_number
          in: query
          required: true
          schema:
            type: string
            title: Card Number
        - name: from_date
          in: query
          required: true
          schema:
            type: string
            format: date-time
            title: From Date
        - name: to_date
          in: query
          required: true
          schema:
            type: string
            format: date-time
            title: To Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BalanceLogModel'
                title: Response Read Balance History Api Balance History Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/withdrawal:
    post:
      tags:
        - transactions
      summary: Withdrawal
      description: |-
        Эндпоинт для снятия денег с карты.

        Args:
            card_number (str): Номер карты.
            amount (Decimal): Сумма.

        Returns:
            TransactionRequest: Новый баланс.
      operationId: withdrawal_api_withdrawal_post
      parameters:
        - name: card_number
          in: query
          required: true
          schema:
            type: string
            title: Card Number
        - name: amount
          in: query
          required: true
          schema:
            anyOf:
              - type: number
              - type: string
            title: Amount
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRequest'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/deposit:
    post:
      tags:
        - transactions
      summary: Deposit
      description: |-
        Эндпоинт для пополнения карты.

        Args:
            card_number (str): Номер карты.
            amount (Decimal): Сумма.

        Returns:
            TransactionRequest: Новый баланс.
      operationId: deposit_api_deposit_post
      parameters:
        - name: card_number
          in: query
          required: true
          schema:
            type: string
            title: Card Number
        - name: amount
          in: query
          required: true
          schema:
            anyOf:
              - type: number
              - type: string
            title: Amount
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRequest'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/verify:
    post:
      tags:
        - transactions
      summary: Verify
      description: |-
        Эндпоинт для повышения лимита после верификации.

        Args:
            card_number (str): Номер карты.
            verified (bool): Подтверждение верификации.
      operationId: verify_api_verify_post
      parameters:
        - name: card_number
          in: query
          required: true
          schema:
            type: string
            title: Card Number
        - name: verified
          in: query
          required: true
          schema:
            type: boolean
            title: Verified
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BalanceLogModel:
      properties:
        card_number:
          type: string
          title: Card Number
        before:
          type: string
          title: Before
        after:
          type: string
          title: After
        changes:
          type: string
          title: Changes
        datetime_utc:
          type: string
          format: date-time
          title: Datetime Utc
      type: object
      required:
        - card_number
        - before
        - after
        - changes
        - datetime_utc
      title: BalanceLogModel
      description: Класс для логов баланса.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    TransactionRequest:
      properties:
        card_number:
          type: string
          title: Card Number
        balance:
          type: string
          title: Balance
      type: object
      required:
        - card_number
        - balance
      title: TransactionRequest
      description: Схема для транзакций.
    UserBalanceRequest:
      properties:
        card_number:
          type: string
          title: Card Number
        balance:
          type: string
          title: Balance
      type: object
      required:
        - card_number
        - balance
      title: UserBalanceRequest
      description: Balance response schema.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
